[package]
name = "rust_micro_benchmark"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"

[dependencies.syn]
version = "2.0.18"
features = [
  'extra-traits',
  'full'
]